[package]
name = "server_aboba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8.0"
anyhow = "1.0.75"
futures = { version = "0.3.29", features = ["thread-pool"] }
